import { AR_One_Sans, Anek_Bangla } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'
import About from './components/About'

const arOne = AR_One_Sans({ subsets: ['latin'] })
const anek = Anek_Bangla({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={anek.className}>
        <Header />
        {children}
        <About />
        <Footer />
      </body>
    </html>
  )
}
